name: Renovate Dependencies

on:
  schedule:
    # https://crontab.guru/#5_12_*_*_1
    - cron: "5 12 * * 1"
  workflow_dispatch:

jobs:
  sync:
    uses: curioswitch/go-build/.github/workflows/export-renovate.yaml@b4bb86391b1e39db0dd8cad98e4d8be49c298077 # v0.6.1
    with:
      github_app_id: "1047503"
    secrets:
      github_app_key: ${{ secrets.CURIOSWITCH_APP_KEY }}
